### PR TITLE
Update ToUppercase.py

### PR DESCRIPTION
**Pull request by ghost**
Try not to mix snakecase(this_is_snake_case) and camelcase(ThisIsCamelCase) together.
e.g. I wouldn't write to_UpperString like what you just did. I would do toUpperString or to_upper_string.
Also, for parameter names try to use snakecase, like input_string rather than inputString

### CODE REVIEW

**Comment by chenmingxue** [comment]
That 

> Try not to mix snakecase(this_is_snake_case) and camelcase(ThisIsCamelCase) together.
> e.g. I wouldn't write to_UpperString like what you just did. I would do toUpperString or to_upper_string.
> Also, for parameter names try to use snakecase, like input_string rather than inputString

**Review by chenmingxue — COMMENTED** [review]
Nice suggestions!

**Comment by chenmingxue** [comment]
Sorry, I carelessly hit the closed button. I will change the code.

> That
> 
> > Try not to mix snakecase(this_is_snake_case) and camelcase(ThisIsCamelCase) together.
> > e.g. I wouldn't write to_UpperString like what you just did. I would do toUpperString or to_upper_string.
> > Also, for parameter names try to use snakecase, like input_string rather than inputString

**Comment by chenmingxue** [comment]
Ok now. Also practiced git functions.

**Comment by ghost** [comment]
Sweet man, get better!

**Pull request merged**
